scrape_configs:
  - job_name: grafana
    scrape_interval: 3s
    static_configs:
      - targets: ["grafana:3000"]

  - job_name: postgres
    scrape_interval: 3s
    static_configs:
      - targets: ["postgres-exporter:9187"]
